name: deepfilter_livekit_example
description: Example app for deepfilter_livekit plugin.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  deepfilter_livekit:
    path: ..
  livekit_client: ^2.7.0
  flutter_webrtc: ^1.4.0
  dart_jsonwebtoken: ^3.4.1

flutter:
  uses-material-design: true
